news_collecting:
  description: >
    Thu thập và tóm tắt 3 bài báo có ảnh hưởng lớn nhất đến thị trường chứng khoán Việt Nam
    trong vòng 3 tháng tính đến ngày hiện tại ({current_date}).

    Quy trình thực hiện:
    1. Sử dụng công cụ `search_tool` để tìm các bài báo liên quan đến tin tức vĩ mô và chính sách kinh tế.
       Ưu tiên kết quả từ các nguồn tài chính uy tín (ví dụ: Cafef, VnEconomy, Bloomberg, VnExpress Kinh Doanh...).
    2. Chọn 3 bài báo tiêu biểu nhất dựa trên mức độ ảnh hưởng, độ tin cậy và mức độ liên quan đến thị trường Việt Nam.
    3. Dùng `scrape_tool` để thu thập nội dung chi tiết của từng bài báo đã chọn.
    4. Tóm tắt nội dung chính của từng bài trong 3–5 câu, tập trung vào tác động đến thị trường chứng khoán.

    Giới hạn:
    - Chỉ chọn bài viết có ngày đăng trong vòng 3 tháng trở lại.
    - Chỉ lấy bài có tiêu đề và nội dung thể hiện rõ ảnh hưởng đến thị trường tài chính/chứng khoán Việt Nam.
  expected_output: >
    Một danh sách dạng markdown gồm 3 mục, mỗi mục bao gồm:
    - Tiêu đề bài báo (in đậm)
    - Ngày đăng
    - Nguồn (kèm liên kết URL)
    - Tóm tắt 3–5 câu bằng tiếng Việt nêu rõ nội dung chính và ảnh hưởng đến thị trường

  agent: stock_news_researcher

fundamental_analysis:
  description: >
    Phân tích cơ bản mã cổ phiếu {symbol} dựa trên các chỉ số tài chính để đánh giá mức định giá và sức khỏe doanh nghiệp.

    Quy trình thực hiện:
    1. Sử dụng công cụ `fund_tool` để thu thập các chỉ số: P/E, P/B, ROE, D/E, EPS, EV/EBITDA, tăng trưởng doanh thu/lợi nhuận, và biên lợi nhuận.
    2. Xác định cổ phiếu thuộc ngành nào.
    3. So sánh P/E và P/B của cổ phiếu với trung bình ngành từ tệp `knowledge/PE_PB_industry_average.json`.
       Nếu ngành chưa có dữ liệu, sử dụng ngành gần nhất tương đương.
    4. Phân tích các chỉ số còn lại để đánh giá hiệu suất hoạt động và mức độ rủi ro tài chính.

    Ngày thực hiện: {current_date}
  expected_output: >
    Một báo cáo bằng tiếng Việt, dài 2–3 đoạn, bao gồm:
    - Nhận định định giá: rẻ / đắt / hợp lý
    - Đánh giá hiệu quả hoạt động tài chính: liệu các chỉ số nằm trong ngưỡng tốt hay không
    - Nhận xét tổng thể về triển vọng kinh doanh

  agent: fundamental_analyst

technical_analysis:
  description: >
    Đánh giá xu hướng giá của cổ phiếu {symbol} trong ngày {current_date} thông qua phân tích kỹ thuật.

    Quy trình thực hiện:
    1. Sử dụng công cụ `tech_tool` để thu thập các chỉ báo: SMA, EMA, RSI, MACD, khối lượng giao dịch, OBV và xác định vùng hỗ trợ/kháng cự.
    2. Xác định xu hướng hiện tại (tăng/giảm/tích lũy).
    3. Đưa ra đánh giá động lượng và khả năng xuất hiện tín hiệu giao dịch.

  expected_output: >
    Một báo cáo bằng tiếng Việt, dài 2–3 đoạn, bao gồm:
    - Nhận định xu hướng hiện tại (tăng/giảm/đi ngang)
    - Phân tích tín hiệu kỹ thuật (ví dụ: RSI quá mua/quá bán, giao cắt MACD...)
    - Đánh giá tổng thể về thời điểm mua bán từ góc nhìn kỹ thuật

  agent: technical_analyst

investment_decision:
  description: >
    Tổng hợp kết quả từ các phân tích (news_collecting, fundamental_analysis, technical_analysis)
    để đưa ra khuyến nghị đầu tư cho mã cổ phiếu {symbol}.

    Quy trình thực hiện:
    1. Tóm tắt ngắn gọn kết quả phân tích vĩ mô, cơ bản, và kỹ thuật.
    2. Đánh giá xem thông tin đang hỗ trợ xu hướng tăng hay giảm.
    3. Đưa ra khuyến nghị rõ ràng: MUA, BÁN, hay GIỮ.
    4. Nếu chưa nên hành động, đề xuất điều kiện cụ thể cần theo dõi (ví dụ: đợi giá vượt kháng cự...).

    Ghi chú: Câu trả lời KHÔNG ĐƯỢC thiếu khuyến nghị rõ ràng, và phải dựa vào cả 3 yếu tố: vĩ mô – cơ bản – kỹ thuật.
  expected_output: >
    Một đoạn văn bằng tiếng Việt (~150–200 từ) có cấu trúc:
    - Mã cổ phiếu, tên công ty và ngành nghề
    - Nhận định vĩ mô (3–4 câu)
    - Đánh giá phân tích cơ bản (3–4 câu)
    - Đánh giá phân tích kỹ thuật (3–4 câu)
    - Kết luận: Mua / Bán / Giữ (in đậm), kèm giải thích rõ ràng.
    - Nếu khuyến nghị là GIỮ: đề xuất điều kiện hoặc thời điểm phù hợp hơn để xem xét lại

  agent: investment_strategist